baseurl: "https://lcpu-club.github.io/"
languageCode: "zh-Hans"
title: LCPU
copyright: LCPU
theme: lcpu
canonifyURLs: true

taxonomies:
  tags: tags

social:
  github: "https://www.github.com/lcpu-club"
  # email: ""

params:
  bio: |
    **L**inux **C**lub of **P**eking **U**niversity

  enableComments: false
  enableRSS: true

  # Add custom assets with their paths relative to the static folder
  customCSS: []
  customJS: []

  # The variables below are optionally too and can be used to
  # translate or customize each string of the theme.

  # Navigation links
  home: ""
  news: "Archive"
  softwares: "Mirrors"
  about: "About"

  links:
    mirrors:
      name: "Mirrors"
      path: "https://mirrors.pku.edu.cn"

  # Pagination links
  olderPosts: ""
  newerPosts: ""
  readMore: ""
  copyright: ""

  # Sharing options and author information in posts
  aboutAuthor: "LCPU"
  tweet: ""
  share: ""

  # 404 page
  title404: ""
  subtitle404: ""
